import {
  ArrowRight,
  Check,
  Circle,
  Copy,
  Edit,
  ExternalLink,
  File,
  HelpCircle,
  Home,
  Loader2,
  Mail,
  MessageSquare,
  Plus,
  PlusCircle,
  Search,
  Server,
  Settings,
  Share2,
  Shield,
  Trash,
  User,
  X,
  Workflow,
  ChevronDown,
  ChevronUp,
  Sun,
  Moon,
  Laptop,
  Languages,
  Menu,
  Instagram,
  Github,
  Linkedin,
  ChevronLeft,
  ChevronRight,
} from "lucide-react";

const Icons = {
  arrowRight: ArrowRight,
  check: Check,
  circle: Circle,
  workflow: Workflow,
  close: X,
  copy: Copy,
  dark: Moon,
  edit: Edit,
  externalLink: ExternalLink,
  file: File,
  help: HelpCircle,
  home: Home,
  light: Sun,
  loader: Loader2,
  mail: Mail,
  messageSquare: MessageSquare,
  plus: Plus,
  plusCircle: PlusCircle,
  search: Search,
  server: Server,
  settings: Settings,
  share: Share2,
  shield: Shield,
  spinner: Loader2,
  trash: Trash,
  user: User,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  sun: Sun,
  moon: Moon,
  laptop: Laptop,
  languages: Languages,
  menu: Menu,
  x: X,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
};

const Social = {
  instagram: Instagram,
  github: Github,
  linkedin: Linkedin,
};

export { Icons, Social };
